# Generated by Django 5.2.8 on 2025-11-23 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BorrowRecord',
            new_name='Borrowing',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_stub',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
