# Generated by Django 5.2.8 on 2025-11-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_rename_borrowrecord_borrowing_remove_book_book_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=3),
        ),
    ]
